### DISCUSSION TITLE
How to get RDT Client to fail downloads that take longer than x amount of time? But Torrent maxiumum lifetime doesnt seem to work for me?

### DISCUSSION THREAD

**Discussion by ICE0124** [rogerfar/rdt-client#574] [Q&A] [answered]
Yes i already know about the "Torrent maxiumum lifetime" setting but it seems to just say "Torrent lifetime of 3 minutes reached" and it doesnt do anything. Im not really sure if im doing something wrong or i dont understand something because it should hit the 3 minutes and then fail the torrent. Real Debrid doesnt have the file cached and is trying to download it but there is no peers so it instantly stalls which then i want it to fail but it just reaches its lifetime and doesnt fail it.
Im not really sure if this is a bug report or just a support post but if its a bug il make a issue bug report for it.

Here is my current settings for arr's 
![image](https://github.com/user-attachments/assets/e73d94d9-77b6-4a3b-9708-31e87f81baf9)

**Comment by rogerfar** [comment]
This seems to work as expected. It indeed will show you that error message and passes that back to Sonarr/Radarr. They need to delete the torrent and fetch another release.

**Reply by ICE0124** [reply]
It was kinda hidden but if you hover over the status icon it shows that RDT Client sent an error but Sonarr and Radarr knows there is an error but doesnt do anything about it. So luckily its not an issue with this program so im going to go search to see if i can fix this on more Sonarr and Radarr related areas.

**Reply by ICE0124** [reply, marked as answer]
Ive found a solution that works pretty well using Decluttarr. Ive set it up so it only downloads Real Debrid files by setting the slow min limit to something like 20,000kbps which for the most part only Real Debrid can hit that download speed. If you dont want that you can also configure it to only delete and research after a torrent has stalled. For the qBittorrent link put the link to your RDT Client instead and it will work.
https://github.com/ManiMatter/decluttarr/

**Reply by vpierre1776** [reply]
> Ive found a solution that works pretty well using Decluttarr. Ive set it up so it only downloads Real Debrid files by setting the slow min limit to something like 20,000kbps which for the most part only Real Debrid can hit that download speed. If you dont want that you can also configure it to only delete and research after a torrent has stalled. For the qBittorrent link put the link to your RDT Client instead and it will work. https://github.com/ManiMatter/decluttarr/

Any idea why I would be getting this api error. Thanks

"[INFO]: *** Check Instances ***
[DEBUG]: Starting new HTTP connection (1): 172.20.10.135:8989
[DEBUG]: http://172.20.10.135:8989 "GET /api/v3/system/status HTTP/11" 200 None
[DEBUG]: Starting new HTTP connection (1): 172.20.10.135:8989
[DEBUG]: http://172.20.10.135:8989 "GET /api/v3/system/status HTTP/11" 200 None
[DEBUG]: Starting new HTTP connection (1): 172.20.10.135:8989
[DEBUG]: http://172.20.10.135:8989 "GET /api/v3/system/status HTTP/11" 200 None
[INFO]: OK | Sonarr
[DEBUG]: Current version of SONARR: 4.0.9.2244
[DEBUG]: Starting new HTTP connection (1): 172.20.10.136:6500
[DEBUG]: http://172.20.10.136:6500 "POST /api/v2/auth/login HTTP/11" 200 None
[DEBUG]: Starting new HTTP connection (1): 172.20.10.136:6500
[DEBUG]: http://172.20.10.136:6500 "GET /api/v2/app/version HTTP/11" 200 None
[INFO]: OK | qBittorrent
[DEBUG]: Current version of qBittorrent: 4.3.2
[INFO]: 
[DEBUG]: Starting new HTTP connection (1): 172.20.10.136:6500
[DEBUG]: http://172.20.10.136:6500 "GET /api/v2/torrents/tags HTTP/11" 404 0
TypeError: argument of type 'NoneType' is not iterable
HTTP Error: 404 Client Error: Not Found for url: http://172.20.10.136:6500/api/v2/torrents/tags
"

**Reply by ecw1973** [reply]
I was having the same issue.   How to make this work was not stated clearly and/or has changed since original post.

I am now using:

```yaml
  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      LOG_LEVEL: VERBOSE
      REMOVE_TIMER: 1
      REMOVE_FAILED: True
      REMOVE_SLOW: True
      REMOVE_STALLED: True
      PERMITTED_ATTEMPTS: 1
      MIN_DOWNLOAD_SPEED: 5000 # KBps.  Adjust as required.
      RADARR_URL: http://radarr:7878
      RADARR_KEY: xxxxxxxxxxxxxxxxxxxxxxxx
      SONARR_URL: http://sonarr:8989
      SONARR_KEY: xxxxxxxxxxxxxxxxxxxxxxxx
      # Skip qBittorrent since we only want it to check RdtClient 
      IGNORED_DOWNLOAD_CLIENTS: '["qBittorrent"]'
```

I have confirmed this works as desired and will remove stalled and very slow downloads from RdtClient and trigger a new search in Radarr/Sonarr.
