### DISCUSSION TITLE
All parameters lost when updating (docker)

### DISCUSSION THREAD

**Discussion by zukato** [rogerfar/rdt-client#580] [Q&A] [answered]
As per the title, when I update the image, all my settings are lost, even the login and password. When going into the folder /data/db folder, it is empty.

What am I doing wrong?

Here is the docker compose (Portainer stack) :
```
rdtclient:
    image: rogerfar/rdtclient:latest
    container_name: rdtclient
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - /mnt/data/torrents:/data/downloads
      - /home/myuser/docker-configs/rdtclient:/data/db'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Europe/Paris"
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 6500:6500
```
