### DISCUSSION TITLE
Unable to deploy in Portainer

### DISCUSSION THREAD

**Discussion by poweredtreble** [rogerfar/rdt-client#805] [General]
Having issues getting this deployed as a stack in portainer. It gives me "missing signature key error", or to be exact:
```
Deployment error
Pulling rdtclient (rogerfar/rdtclient:2.0.102)... missing signature key
```
I copy pasted the docker compose script from the docker readme file (and modified it for my uid/gid/folders etc). The docker instructions don't seem to have been updated in 4 years - perhaps there's something that needs changing?

**Comment by Cucumberrbob** [comment]
What version of docker are you running? You can find out by running `docker version`.

**Reply by poweredtriple** [reply]
Sorry, different account but I am the OP.

An out-of-date docker version was most likely the issue. I encountered a similar issue installing syncthing on the same device, and eventually figured out that I got this "missing signature key" error in newer versions of syncthing. I installed an older version of syncthing, and managed to get it up and running.

I'll try and give this another go at some point.

(The reason I had an old version of Docker in the first place is because my NAS is by Terramaster, and the OS it runs [Stock Terramaster OS called TOS] is no longer receiving support or updates. Will eventually buy a new NAS, or try to put in my own OS onto this device, at some point in the near future.)

**Comment by TimboZero** [comment]
Getting a similar problem (installing to portainer) but different error
```
Failed to deploy a stack: failed to load the compose file: service "rdtclient" refers to undefined volume &lt;path to data&gt;: invalid compose project
```

I did as advised above and checked my docker version
Client: Docker Engine - Community
 Version:           28.0.4
 API version:       1.48

i used the following compose script
```
---
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1000
      - PGID=100
      - TZ=CET
    volumes:
      - <path to data>:/NAS/AppData
      - <path to downloads>:/media
    ports:
      - 6500:6500
    restart: unless-stopped
```

Any help appreciated, thank you
