### ISSUE TITLE
Radarr Path issue

### ISSUE THREAD

**Issue by dsxcsman** [rogerfar/rdt-client#149]
First, thank you very much for your nice work. I really enjoy this project and i hope you will continue.

**What version are you using?**

Docker Image image rogerfar/rdtclient version v2.0.16

**What OS are you running?**

Synology DSM (linux base)

**Are you using Docker or as a service?**

Using docker compose 

```
rdtclient:
        container_name: rdtclient
        network_mode : host
        environment:
        - PUID=1050
        - PGID=100
        - TZ=Europe/London
        ports:
        - 6500:6500 # WebUI rdtclient
        volumes:
        - /volume1/media/downloads/:/downloads
        - /volume1/docker/downloads-vpn/rdt-client/config:/data/db
        image: rogerfar/rdtclient
       
        logging:
            driver: json-file
            options:
                max-size: 10m
        restart: unless-stopped
```
Download works perfectly but i have difficulties to move files at the end of the download. 

I've got the following message with talking about Windows but i'm on linux.

![image](https://user-images.githubusercontent.com/5779819/170882515-59007c3f-1cc3-4438-9fec-b0de46f617b3.png)
