### ISSUE TITLE
Help with paths please

### ISSUE THREAD

**Issue by ikrowni** [rogerfar/rdt-client#188]
Hello I just purchased an NAS and coming from a windows setup im having some issues with the paths.

I installed rdtclient using docker compose 

```
version: "3.3"
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /volume1/docker/rdtclient:/data/db
      - /volume1/data/downloads:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped
```

Here are the settings I have inside rdtclient
![image](https://user-images.githubusercontent.com/4442098/196021205-b1fb0451-4e21-49e4-b3a4-033a1d5708e8.png)

For some reason when I start a download in sonarr the show ends up going into the wrong folder

It ends up here
` /data/sonarr/`

But it needs to be here
` /data/downloads/sonarr`
