### ISSUE TITLE
Unwanted /data volume hogs system

### ISSUE THREAD

**Issue by janaxhell** [rogerfar/rdt-client#213]
Yesterday :latest build broke something and at the end of the day it was solved with 2.0.21. But today I see a new problem.

I have these volumes set:

```
/srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/rdtclient:/config
/srv/dev-disk-by-uuid-2628F1C228F19153/data/db:/data/db
/srv/dev-disk-by-uuid-2628F1C228F19153/data/rdtclient:/data/rdtclient
/srv/dev-disk-by-uuid-A870CA6B70CA3FB4/data/rdtclient:/data2/rdtclient
```
But each time I recreate RDTclient, it creates this one:

`/srv/dev-disk-by-uuid-2628F1C228F19153/data/rdtclient:/data`

that is redundant because I have already set
`/srv/dev-disk-by-uuid-2628F1C228F19153/data/rdtclient:/data/rdtclient`
and I specifically don't want it because it makes rdtclient check permissions of thousands of files inside /data.
But no matter what, if I remove it from container, it reappears at start.
I created 
```
[...]:/data/rdtclient
[...]:/data2/rdtclient
```
that are 2 separate drives to limit permission check to just /rdtclient folder. And it worked fine until 2.0.19.
Now it hogs the system again, but this time log says nothing about it (like "Setting Permissions"), I can only hear the HDD thrashing and see rdclient abusing CPU, RAM and SystemLoad from Grafana for one movie waiting to be imported in Radarr for no less than 20 minutes.  

My compose looks like this

```
version: '3.3'
services:
    rdtclient:
        container_name: rdtclient
        environment:
        - PUID=998
        - PGID=100
        volumes:
            - '/srv/dev-disk-by-uuid-2628F1C228F19153/data/rdtclient:/data/rdtclient'
            - '/srv/dev-disk-by-uuid-A870CA6B70CA3FB4/data/rdtclient:/data2/rdtclient'
            - '/srv/dev-disk-by-uuid-2628F1C228F19153/data/db:/data/db'
            - '/srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/rdtclient:/config'
        image: rogerfar/rdtclient
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '6500:6500'
```
As you can see I haven't set /srv/dev-disk-by-uuid-2628F1C228F19153/data/rdtclient:/data anywhere, nevertheless it reappears in container volumes as shown in picture below.

**What version are you using?**
2.0.21
**Wat OS are you running?**
OMV6
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**

![vivaldi_mlDfKCLKXQ](https://user-images.githubusercontent.com/55061479/224287998-b6b1162c-5742-4a59-9aa3-5c80c18bcded.png)

EDIT Happened again with Sonarr. This definitely didn't happen before 2.0.21

EDIT 2 I reverted back to 2.0.19, but it keeps happening. This is the log

```
[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service 00-legacy successfully started
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    998
User gid:    100
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
Setting permissions
chown: WARNING: Circular directory structure.
This almost certainly means that you have a corrupted file system.
NOTIFY YOUR SYSTEM MANAGER.
The following directory is part of the cycle:
  /data/rdtclient
cont-init: info: /etc/cont-init.d/30-config exited 1
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun rdtclient (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
Changing to /app folder
Starting rtdclient
[13:03:29 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[13:03:30 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[13:03:30 WRN] No XML encryptor configured. Key {40eb9666-a151-428a-9eef-ad35863f181b} may be persisted to storage in unencrypted form.
[13:03:30 WRN] Starting host on version 2.0.19.0
[13:04:07 WRN] The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
[13:04:07 WRN] 401: /Api/Authentication/IsLoggedIn
```
