### ISSUE TITLE
rdt-client unhealthy

### ISSUE THREAD

**Issue by ElPenguin** [rogerfar/rdt-client#225]
**What version are you using?**
Since 2.0.20
**Wat OS are you running?**
Rocky Linux 8.6
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**
s6-rc-compile: fatal: cyclic service dependency reached from legacy-services and involving legacy-services
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111
**Docker compose**
```
  rdtclient:
    container_name: rdtclient
    labels:
      - traefik.enable=true
      - traefik.http.routers.rdtclient.rule=Host(`rdtclient.mywebsite.com`) 
      - traefik.http.routers.rdtclient.tls=true
      - traefik.http.routers.rdtclient.tls.certResolver=myresolver
      - traefik.http.routers.rdtclient.entrypoints=websecure
      - traefik.http.services.rdtclient.loadbalancer.server.port=6500
    networks:
      - traefik-public
    environment:
      - *PID
      - *GID
      - *TZ
    volumes:
      - rdtdata:/data
      - rdtconfig:/config
      - downloads:/data/downloads
      - rdtDb:/data/db
    image: rogerfar/rdtclient:2.0.20 #same on 21/22/23
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '6500:6500'
    pull_policy: always
    healthcheck:
      test: [ "CMD", "curl", "-f" ,"http://localhost:6500"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
```
