### ISSUE TITLE
help please for destination already exist

### ISSUE THREAD

**Issue by kristobal62** [rogerfar/rdt-client#257]
**What version are you using? 2.0.30

**Wat OS are you running? VM debian

**Are you using Docker or as a service? linux

**Please attach a log file here with the log setting set to debug**
![image](https://github.com/rogerfar/rdt-client/assets/58385012/7b097cbd-0783-4a5b-89c3-9498f13e551d)

Hello, 
Hello, I use radarr and sonarr with the internal downloader.
When I download a movie for example, it downloads fine, it is imported correctly into the movies directory but I still get the error message "failled to import movie, destination already exists"
If I use qbitorrent I have no problem.

Here is my setup

![image](https://github.com/rogerfar/rdt-client/assets/58385012/91b1c4ff-f8df-45f0-a741-0d829b4c997b)
the directory "temp" is for the tempory download.
![image](https://github.com/rogerfar/rdt-client/assets/58385012/45b9e48b-5093-48ee-87d9-d41919b56725)

![image](https://github.com/rogerfar/rdt-client/assets/58385012/6e41c7b3-bad4-467e-917d-3d8be12aeb85)
even if I delete the mapping it's the same problem.

![image](https://github.com/rogerfar/rdt-client/assets/58385012/9ee13312-003f-41a3-9cdb-dba82e984d06)

When I look in the movies directory, the AKA movie is there.
![image](https://github.com/rogerfar/rdt-client/assets/58385012/5ee05e56-d981-4990-a21c-8d9304c333e8)

![image](https://github.com/rogerfar/rdt-client/assets/58385012/33698e62-e8d6-4e49-a6ee-8bee2ce48708)
![image](https://github.com/rogerfar/rdt-client/assets/58385012/b6e785be-9e7f-48fe-9d05-c662b9866e29)
![image](https://github.com/rogerfar/rdt-client/assets/58385012/404de1da-d020-44bb-ace9-f36deaace8b9)
![image](https://github.com/rogerfar/rdt-client/assets/58385012/e4262cbb-9b89-49a6-98b1-4469ed152b4a)

Thank you for your help as I am a newbie.

**Comment by rogerfar** [comment]
You might have to look in the radarr logs to see what is happening there.

**Comment by hrenaud** [comment]
Hello,
I have exactly the same problem, were you able to solve it @kristobal62 ?

Thanks in advance.

**Comment by kristobal62** [comment]
Bonjour,
Tu es français ?

Christophe
________________________________

**Comment by rogerfar** [comment]
Please post logs, but this seems to be a sonarr issue perhaps? Check those logs too.

**Comment by hrenaud** [comment]
@kristobal62 Bonjour, oui. Mon accent m'a trahit ? :)

@rogerfar Hello, thank you for your reply.

I've just fixed the problem. It was a writing rights problem.

I had to change the docker-compose.yml to configure them. It would be nice to add this information to the documentation.



```yml
version: '3.3'
services:
    rdtclient:
        container_name: rdtclient
        volumes:
            - '${DOCKERSTORAGEDIR}:/data:rw'
            - '${DOCKERCONFDIR}/rdt-client/:/data/db'
        image: rogerfar/rdtclient
        restart: always
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
        logging:
            driver: json-file
            options:
                max-file: ${DOCKERLOGGING_MAXFILE}
                max-size: ${DOCKERLOGGING_MAXSIZE}
        ports:
            - '6500:6500'
        healthcheck:
            test: curl --fail http://localhost:6500 || exit 1
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 30s
```
