### ISSUE TITLE
RDT-Client Unhealthy after mass download

### ISSUE THREAD

**Issue by subexx** [rogerfar/rdt-client#326]
I have imported a trakt list to radarr. RDT-Client became unhealthy in the middle of downloads. I restared the container and it started working again after some time. Don't if that was the trigger but i am having so much trouble with it right now.. If i reboot it will say starting then unhealthy after few minutes. if i leave it alone for long time it will eventually start. I have tried everything. Deleted all the folders and completely started a new container from scratch but same issue. Could you please help me fix. i have played around with file ownerships and all. it looks fine. while troubleshooting i noticed it ignores the user and group i given in the compose file and running as root user. Is it supposed to be like that? It used to work well until couple of days ago. Bleo wi my compose file. I am running it in ubuntu 22.4. Please help.

```
version: "3.7"
services:
  rdtclient:
    container_name: rdtclient
    volumes:
      - /home/ubuntu/docker/rdtclient/data:/data/db
      - /home/ubuntu/docker/rdtclient/downloads:/downloads
    image: rogerfar/rdtclient
    restart: always
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Melbourne
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 6500:6500

```

```
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 
  Based on images from linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1001
User GID:    1001
───────────────────────────────────────
Setting permissions
[custom-init] No custom files found, skipping...
Setting permissions
Changing to /app folder
Starting rtdclient
[ls.io-init] done.
```

**Comment by rogerfar** [comment]
Try to get some logs, otherwise delete your container (and volumes) and re-setup. Enable debug logging and try again.

**Comment by Ikario** [comment]
Hey, just chiming in saying I have what I think is the same issue after version 2.0.46.  Deleting everything, volumes, containers and starting from scratch is not working however if I change my docker compose to exactly that version (or previous ones) it works perfectly.  Everything else after that, doesn't. This is my docker compose (which, again, works perfectly fine up until and including 2.0.46):
```

version: "3.6"
services:
    rdtclient:
        container_name: rdtclient
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}            
        volumes:
            - '${MEDIA}/downloads/complete:/data/downloads'
            - '${DOCKERCONFIG}/rdtclient:/data/db'
        image: rogerfar/rdtclient
        networks:
            - medianet
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '6500:6500' 

```

I did try replacing the variables with the paths, however that is not the issue as it still doesn't work for anything after 2.0.46.  No log is generated, however when running it not detached, this is the output:

```
rdtclient  | [migrations] started
rdtclient  | [migrations] no migrations found
rdtclient  | usermod: no changes
rdtclient  | ───────────────────────────────────────
rdtclient  |   _____ __ __ _____ _____ _____ _____
rdtclient  |  |     |  |  |   __|_   _|     |     |
rdtclient  |  |   --|  |  |__   | | | |  |  | | | |
rdtclient  |  |_____|_____|_____| |_| |_____|_|_|_|
rdtclient  |        _____ __ __ _ __    ____
rdtclient  |       | __  |  |  | |  |  |    \
rdtclient  |       | __ -|  |  | |  |__|  |  |
rdtclient  |       |_____|_____|_|_____|____/
rdtclient  |
rdtclient  |   Based on images from linuxserver.io
rdtclient  | ───────────────────────────────────────
rdtclient  |
rdtclient  | To support LSIO projects visit:
rdtclient  | https://www.linuxserver.io/donate/
rdtclient  |
rdtclient  | ───────────────────────────────────────
rdtclient  | GID/UID
rdtclient  | ───────────────────────────────────────
rdtclient  |
rdtclient  | User UID:    1000
rdtclient  | User GID:    1000
rdtclient  | ───────────────────────────────────────
rdtclient  |
rdtclient  | Setting permissions
rdtclient  | [custom-init] No custom files found, skipping...
rdtclient  | Setting permissions
rdtclient  | Changing to /app folder
rdtclient  | Starting rtdclient
rdtclient  | s6-applyuidgid: fatal: unable to exec dotnet: No such file or directory
rdtclient  | [ls.io-init] done.
rdtclient  | Setting permissions
rdtclient  | Changing to /app folder
rdtclient  | Starting rtdclient
rdtclient  | s6-applyuidgid: fatal: unable to exec dotnet: No such file or directory
```

Last four lines keep on repeating endlessly after that.  If there's anything that I could do to help you debug this, let me know and thanks!
