### ISSUE TITLE
Access to the path '/tmp/' is denied

### ISSUE THREAD

**Issue by DaGloaDone** [rogerfar/rdt-client#371]
Hey :)

So i moved my Docker and now i have this issue: Access to the path '/tmp/' is denied.
My docker compose looks like this:

```
version: '3.3
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/Berlin
    volumes:
      - /STICK/appdata/rdtcient:/data/db
      - /HDD/downloads:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped
```

**What version are you using?**
Docker: rogerfar/rdtclient

**Wat OS are you running?**
Debian 11

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
RealDebrid

**Please attach a log file here with the log setting set to debug**
[_rdtclient_logs.txt](https://github.com/rogerfar/rdt-client/files/13582758/_rdtclient_logs.txt)
