### ISSUE TITLE
'unable to open database file' when using docker

### ISSUE THREAD

**Issue by ravensorb** [rogerfar/rdt-client#41]
I am running into a permissions issue when using the docker image.  I have mapped a local folder into the container and confirmed the folder is set to full permissions (tried 766 and 777) -- neither work.  Am I missing something?

```
version: "3.7"

services:

  rdtclient:
    # https://hub.docker.com/r/rogerfar/rdtclient
    container_name: rdtclient
    image: rogerfar/rdtclient
    volumes:
      - ./data/dbt:/data/db:rw 
      - ./data/downloads:/data/downloads:rw 
    networks:
      - media 
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
    security_opt:
      - no-new-privileges:true
```
