### ISSUE TITLE
Is there any way to make it NOT use a docker volume?

### ISSUE THREAD

**Issue by flavorgold1** [rogerfar/rdt-client#422]
I'm on `[Ubuntu 22.04.3 LTS (Jammy Jellyfish)](https://releases.ubuntu.com/jammy)`:

This is my `docker-compose.yml` file:

```
services:
  rdtclient:
    container_name: rdtclient
    image: rogerfar/rdtclient:latest
    network_mode: host
    volumes:
      - /home/username/docker_dir/rdtclient/db:/data/db
      - /home/username/Downloads:/data/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT
    restart: unless-stopped
```

When I run `sudo docker ps -a --filter volume=$(sudo docker volume ls --quiet)`, it shows the following:

```
CONTAINER ID   IMAGE                       COMMAND   CREATED        STATUS                  PORTS     NAMES
xxxxxxxxxxxx   rogerfar/rdtclient:latest   "/init"   47 hours ago   Up 24 hours (healthy)             rdtclient
```

I don't want to have docker volumes be used.

How do I make it not use a docker volume?
