### ISSUE TITLE
Torrents tuck on queued for download

### ISSUE THREAD

**Issue by Nebzla** [rogerfar/rdt-client#435]
Hello, I'm currently trying to configure RDT and am running into issues with it actually downlaoding to my system while running under docker. I'm 99% sure my file paths are all setup correctly, which is the only other mention I can find of this problem being reproduced in the past.

![image](https://github.com/rogerfar/rdt-client/assets/77118926/6e28d0eb-fad6-415f-8854-0409b4064675)

Heres the docker compose file (rdtclient is under services) that is associated with it.

```
MEDIADIR=/home/will/Videos
STACKDIR=/home/will/Documents/Mediaserver/media-stack
```
```
  rdtclient:
    container_name: rdtclient
    volumes:
      - $MEDIADIR:/temp
      - $STACKDIR/rdt-client:/data/db
    image: rogerfar/rdtclient
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    # ports:
    #   - "6500:6500"
    network_mode: "service:gluetun"

```

Version: 2.0.6.3 

OS: Arch Linux

Using Docker

Provider: Real Debrid

Downloader: Internal Downloader

Logs (Doesn't seem like there's much going on, this is from starting the docker container to requesting a movie):
```
2024-03-15 22:13:13.232 +00:00 [WRN] RdtClient.Service.BackgroundServices.Startup: Starting host on version 2.0.63.0
2024-03-15 22:13:26.566 +00:00 [WRN] : 304: /index.html

```
