### ISSUE TITLE
Run external program on torrent completion failing with "working directory '/app'. Exec format error"

### ISSUE THREAD

**Issue by ianweatherburn** [rogerfar/rdt-client#437]
**What version are you using?**
v2.0.63

**What OS are you running?**
Ubuntu 22.04.4 LTS

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using
Realdebrid

**Which downloader are you using?**
Sonarr/Radarr

**Please attach a log file here with the log setting set to debug**
[_rdtclient_logs.txt](https://github.com/rogerfar/rdt-client/files/14632075/_rdtclient_logs.txt)
?**

**ERROR**: Attempting to execute a bash script upon completion of torrent download.
The bash script is in the container shared folder bind, /data

**`An error occurred trying to start process '/data/rdt_pushover.sh' with working directory '/app'. Exec format error`**

"Run external program on torrent completion":
`/data/rdt_pushover.sh`
"External program arguments":
%N %L %F %D %C %Z

For now, the script has 777 in case that was an issue:
`-rwxrwxrwx 1 iwadmin  467 2024-03-18 08:30 rdt_pushover.sh*`

This script attempts to call another bash script to do the actual pushover (api keys removed):
```
!/bin/bash
title="$1"
text="Torrent ($1). Category ($2). Content Path ($3). Save Path ($4). File-Count ($5). Size ($6)."
/pushover/pushover.sh -u ... -t ... -m "$text" -T "$title"
exit 0
```

/pushover is made available as a bind in the container as well so it can find that script.

```
rdtclient:
    image: 'rogerfar/rdtclient:latest'
    container_name: rdtclient
    hostname: rdtclient
    restart: unless-stopped
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '${RDT_CLIENT}:6500'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${MNT}:/mnt'
      - '${DATA}/rdtclient/data:/data'
      - '${DATA}/rdtclient/data/downloads:/data/downloads'
      - '${DATA}/rdtclient/data/db:/data/db'
      - '/usr/local/bin/pushover:/pushover'
```
