### ISSUE TITLE
New version of Docker won't start

### ISSUE THREAD

**Issue by minus1kelvin** [rogerfar/rdt-client#51]
I had updated to the new version 1.7.3 in the Docker and it will not load. The previous version was working fine besides a few times I had to restart it due to the "waiting for torrent selection" issue. Sadly, my Docker-fu is weak and I don't know how to get the previous version (I use rogerfar/rdtclient:latest but I can't figure out how to get the 1.7.2, sorry I'm a newbie).

**Comment by rogerfar** [comment]
What host are you running on?

**Comment by minus1kelvin** [comment]
Synology DSM6

**Comment by popophobia** [comment]
I think there is some error with the new build. The docker image is only about a third of the size of the previous version - 261.7 MB vs. 682.7 MB

There is a way to get around it, assuming you have an old version of 1.7.2 cached in your local computer. You can tag it as a specific local version and call docker-compose from there

`docker tag 78d6871d61de rdtclient:1.7.2`

`78d6871d61de` is the image ID of the previous version. Subsequently, you can start docker-compose but refer to `image: rdtclient:1.7.2` instead of `image: rogerfar/rdtclient`

This should tie you over until the problem is fixed.

**Comment by rogerfar** [comment]
1.7.3 was build with the old dockerfile again, the 1.7.2 build was using the new linuxserver.io build, but that broke ARM support, so for now it's back to the working docker build again.

**Comment by popophobia** [comment]
I see. I'm running 1.7.2 on Synology DSM (x86) without any issue, but I couldn't start the previous version or 1.7.3.

Hopefully the ARM build will get sorted out with the linuxserver.io base image. Their suite is very versatile :)

Thanks for the cool app. I'm sticking with 1.7.2 for now since it works well on my system atm.

**Comment by minus1kelvin** [comment]
> 1.7.3 was build with the old dockerfile again, the 1.7.2 build was using the new linuxserver.io build, but that broke ARM support, so for now it's back to the working docker build again.

Ok so that means 1.7.3 (latest) should work again or do I need to go the route of using the cached version of 1.7.2? Thanks again!

**Comment by ravensorb** [comment]
I pushed one under my account if you want to test it out: https://hub.docker.com/r/ravensorb/rdtclient

**Comment by rogerfar** [comment]
I pushed 1.7.4 docker too, after the pull request.

The only thing I didn't see what a specific 1.7.4 tag, not sure if that one will popup on the next release or is it not in the publish script?

**Comment by ravensorb** [comment]
Are you using the ps script I added?  If so it has a new param for Version that will tag the image (if you don't specify it, it only tags it as latest, if you do it tags it with both)

**Comment by rogerfar** [comment]
I did use it yes, but didn't call it with a parameter no, maybe I should read the docs 😄

**Comment by timcoop3r** [comment]
fwiw, 1.7.4 wont start for me. The docker logs repeat the following every second:

```
: No such file or directory bash
```

All previous versions have started without issues.

Docker host is x86 running Fedora 33, Docker 20.10.6. Starting using docker-compose below (paths and IP addressing removed)

```
  rdtc:
    container_name: rdtc
    image: rogerfar/rdtclient
    restart: unless-stopped
    user: 1003:1003
    environment:
      TZ: Europe/London
      http_proxy: http://x.x.x.x:8888
      https_proxy: http://x.x.x.x:8888
    volumes:
      - /downloads:/data/downloads:
      - /db:/data/db:
    ports:
      - "6500:6500"
    network_mode: bridge
 ```

**Comment by timcoop3r** [comment]
Updated compose to adapt to the new linuxserver.io user workaround rather than the 'user: xxxx:xxxx' config as follows, still have the same error as reported above so I don't this is related to the startup problem?

```
  rdtc:
    container_name: rdtc
    image: rogerfar/rdtclient
    restart: unless-stopped
    environment:
      TZ: Europe/London
      http_proxy: http://x.x.x.x:8888
      https_proxy: http://x.x.x.x:8888
      PUID: 1003
      PGID: 1003
    volumes:
      - /downloads:/data/downloads:
      - /db:/data/db:
    ports:
      - "6500:6500"
    network_mode: bridge
```

Separate note that it might be worth upgrading the readme or release notes to advise that the config format for permissions settings/container user has changed for docker users as other people might be using the container with the 'user' config that doesn't seem compatible with the new changes?

**Comment by ravensorb** [comment]
@timcoop3r  - Can you try the temp one that I published at ravensorb/rdtclient:latest  (everything else can stay the same -- just change the image name)

**Comment by timcoop3r** [comment]
> @timcoop3r - Can you try the temp one that I published at ravensorb/rdtclient:latest (everything else can stay the same -- just change the image name)

Yep that's starting normally

**Comment by ravensorb** [comment]
Ok, thanks.  Interesting thing is -- I just do a git clone off the main repo, built locally, and ran the image and it also worked without issue.  Granted, I am doing the build on linux -- wonder if there is an odd "line ending" issue when building on windows?

**Comment by rogerfar** [comment]
Yeah I think that's a good idea.

**Comment by phirestalker** [comment]
> I think there is some error with the new build. The docker image is only about a third of the size of the previous version - 261.7 MB vs. 682.7 MB
> 
> Id	Tags	Size	Created
> sha256:2b712cc832731f07fb65908915bdad...	rogerfar/rdtclient:latest	261.7 MB	2021-04-20 05:48:16
> sha256:78d6871d61dec21ce59a7f70b4b68b...	rdtclient:1.7.2	682.7 MB	2021-04-15 06:19:47
> There is a way to get around it, assuming you have an old version of 1.7.2 cached in your local computer. You can tag it as a specific local version and call docker-compose from there
> 
> `docker tag 78d6871d61de rdtclient:1.7.2`
> 
> `78d6871d61de` is the image ID of the previous version. Subsequently, you can start docker-compose but refer to `image: rdtclient:1.7.2` instead of `image: rogerfar/rdtclient`
> 
> This should tie you over until the problem is fixed.

When I do that it says the image has been removed and something about losing data in the volumes. Is there another way to roll back until this is fixed?

**Comment by ravensorb** [comment]
The size difference is due to using a different base image -- we moved from the microsoft dot net image to a linuxserver.io base image which is substantially smaller.  The fix seems to be working in my test env, so I'll submit a PR tomorrow with the updated dockerfile and that should get everything working again.

**Comment by Gotcha007** [comment]
re-created my docker container and pulled the latest image but still having the same issue
exec: fatal: unable to exec bash: No such file or directory

**Comment by ravensorb** [comment]
@rogerfar just pushed a pr that now has dos2unix process the scripts files after they are copied into the container

@Gotcha007 if you need something now, you can pull [this image down](https://hub.docker.com/repository/docker/ravensorb/rdtclient)

**Comment by rogerfar** [comment]
I have published the new image with the patches, so if you pull now it should be all good.

**Comment by phirestalker** [comment]
I get this with the new image.
```
Starting rtdclient
./run: line 13: /usr/bin/s6-setuidgid: Permission denied
./run: line 13: exec: /usr/bin/s6-setuidgid: cannot execute: Permission denied
```
My docker-compose.yml is as follows:

```
version: '3.3'
services:
    rdtclient:
        container_name: rdtclient
        user: 1000:1000
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /mnt/media/downloads:/data/downloads
            - db:/data/db
        image: rogerfar/rdtclient:latest
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '6500:6500'
volumes:
    db:
```
