### ISSUE TITLE
While treying to run the client through a VPN contianer, i recieve this error: error response from daemon conflicting options hostname and the network mode

### ISSUE THREAD

**Issue by Condorthefox** [rogerfar/rdt-client#584]
**What version are you using?** latest

**Wat OS are you running?** Casaos

**Are you using Docker or as a service?** Docker

**Which debrid provider are you using?** Real-Debrid

**Which downloader are you using?** internal

**Please attach a log file here with the log setting set to debug**
name: rdtclient
services:
  rdtclient:
    cpu_shares: 50
    command: []
    container_name: rdtclient
    deploy:
      resources:
        limits:
          memory: 7791M
        reservations:
          memory: "67108864"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
      - UMASK=002
    hostname: rdtclient
    image: rogerfar/rdtclient:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/RDTClient/icon.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/4TBNas/data/media
        target: /data/media
      - type: bind
        source: /DATA/AppData/rdtclient/db
        target: /data/db
    ports: []
    devices: []
    cap_add: []
    network_mode: container:gluetun
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: calganaygun
  category: Downloader
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/RDTClient/icon.png
  index: /
  is_uncontrolled: false
  port_map: "6500"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/RDTClient/screenshot-1.png
  store_app_id: rdtclient
  title:
    custom: ""
    en_us: Real-Debrid Torrent Client

**Comment by Koomongous** [comment]
This isn't for rdt-client, but your setup should look like this. Just replace the qbittorrent stuff with rdt-client.
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8123:8123 # qbittorrent
      - 8700:8000 # control server
    volumes:
      - //gluetun:/gluetun
#      - //gluetun/forwarded_port:/tmp/gluetun/forwarded_port
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - TZ=Europe/London 
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - VPN_PORT_FORWARDING=on
#      - HTTPPROXY=off #change to on if you wish to enable
#      - SHADOWSOCKS=off #change to on if you wish to enable
      #- FIREWALL_VPN_INPUT_PORTS=
      # PIA:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_REGIONS=
    restart: unless-stopped 
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8123
      - TORRENTING_PORT=
    volumes:
      - //qbittorrent:/config
    restart: unless-stopped
    depends_on:
      - gluetun
    network_mode: service:gluetun
```
