### ISSUE TITLE
Issue with Remote Path Mapping on Docker Setup for rdt-client and Radarr

### ISSUE THREAD

**Issue by AntoineTROOVY** [rogerfar/rdt-client#642]
**Title**: Issue with Remote Path Mapping on Docker Setup for rdt-client and Radarr  

**Description**:  
I am encountering an issue with remote path mapping when using Radarr with rdt-client in a Docker environment. Radarr is showing the following error:

```
You are using docker; download client rdt-client places downloads in C:\Downloads\radarr but this is not a valid alpine path. Review your remote path mappings and download client settings.
```

**Setup Information**:  
- **Docker**: Yes (running via Docker Compose)  
- **Host OS**: QNAP NAS
- **Docker Containers**:  
  - `rdt-client`  
  - `Radarr`  
- **Volume Bindings**:  
  - rdt-client and Radarr share the following volume bindings:  
    - `/data/downloads` -> `/share/CACHEDEV1_DATA/Plex/Media/Films & Series/Downloads`  
    - `/data/db` -> `/share/CACHEDEV1_DATA/Public/rdt_client`  

```yaml
services:
  rdt-client:
    image: rogerfar/rdtclient
    volumes:
      - /share/CACHEDEV1_DATA/Plex/Media/Films & Series/Downloads:/data/downloads
      - /share/CACHEDEV1_DATA/Public/rdt_client:/data/db

  radarr:
    image: linuxserver/radarr
    volumes:
      - /share/CACHEDEV1_DATA/Plex/Media/Films & Series/Downloads:/download
```

**Questions/Requests**:  
1. Is there a known issue with path handling between rdt-client and Radarr in Docker setups?  
2. How can I configure Remote Path Mapping in Radarr correctly to handle this case?  
3. Is there any specific configuration for rdt-client required to avoid using Windows paths (`C:\Downloads\radarr`) when running in Docker?  

Any guidance on how to resolve this would be greatly appreciated.
