### ISSUE TITLE
FE not writing login + API details to .db file

### ISSUE THREAD

**Issue by sgrenzh** [rogerfar/rdt-client#743]
**What version are you using?**
v2.0.102

**Wat OS are you running?**
OMV 7.7.0-2 (Sandworm)

**Are you using Docker or as a service?**
Docker via docker-compose

**Which debrid provider are you using?**
RDT

**Which downloader are you using?**

---
**Steps + Context**: 
1. Clean OMV installation, with docker-compose to run my docker stack via GUI.
2. Installation of latest rdt-client v2.0.102 via YML with root (PUID=0 PGID=0) and adjusted data and db paths - can confirm all relevant locations exist, are accessible and writable (confirmed via testfile created via SSH Shell), great.
3. I navigate to http://XXX.XXX.X.XXX:6500, am prompted for RDT login details + API key.
4. I enter the correct details. The first glitch I've noticed is once I've added the API key, the login form resets asking me to login again. Once done, I can see on the landing page that **PREMIUM STATUS** is not shown. Also in /profile it says "Error saving:" at the bottom. ![Image](https://github.com/user-attachments/assets/d6b995d6-088e-410f-854d-2729288aafd1)
5. If I enter my login details again via /profile, I get a success message at the bottom. However when returning to the landing page, again the **PREMIUM STATUS** is not shown.

**Issue**:
- It appears that the FE does NOT correctly write to the .db file. On closer inspection of the file, entries for General:UserName, General:PasswordHash, and ApiKey remain unset, regardless of what I've entered via GUI on first login OR later updated via /profile.
- Can confirm all locations exist, are accessible, and writable as root.
- The only fix I found was to manually inject ApiKey, General:UserName, and General:PasswordHash fields into my .db file via sqlite3 . That has done the trick, but it's no ideal.

Anyone has any clue re what's going on? Never has this issue before with other releases.

**My YML**

```
version: '3.3'

services:
    rdtclient:
        image: rogerfar/rdtclient
        container_name: rdtclient
        environment:
            - PUID=0
            - PGID=0
        volumes:
            - /srv/dev-disk-by-uuid-1985920c-d3af-45e0-9970-094b6d9ede9d/0_Downloads:/data/downloads
            - /srv/dev-disk-by-uuid-108ccbf1-553d-42f4-9637-a047d8a94406/data/docker/RDT-Client:/data/db
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - "6500:6500"
        healthcheck:
            test: curl --fail http://localhost:6500 || exit 1
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 30s

```
