### ISSUE TITLE
Input string was not in a correct format. Failure to parse near offset 135. Format item ends prematurely.

### ISSUE THREAD

**Issue by Carter-LL** [rogerfar/rdt-client#762]
**What version are you using?**
2.0.102

**What OS are you running?**
Docker on Ubuntu

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
RealDebrid

**Which downloader are you using?**
Internal

**Please attach a log file here with the log setting set to debug**
[log.txt](https://github.com/user-attachments/files/19372998/log.txt)

![Image](https://github.com/user-attachments/assets/87baf490-20fd-4220-970f-cbb2b8c13d19)

![Image](https://github.com/user-attachments/assets/44b30ad4-04a1-4da5-b6bf-c8e63d99064f)

![Image](https://github.com/user-attachments/assets/ab348ca0-ac6d-4a18-bae1-8ac44708bcd7)

![Image](https://github.com/user-attachments/assets/835db262-2fd7-4ffd-a149-e0c112594f10)

```
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: Sonarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/akeno/thing/configs/sonarr:/config
      - /mnt/akeno/thing:/data
      - /mnt/SharedMedia:/sharedmedia

rdtclient:
    image: rogerfar/rdtclient
    container_name: RdtClient
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/akeno/thing/configs/rdt:/data/db
      - /mnt/SharedMedia:/sharedmedia
    logging:
       driver: json-file
       options:
          max-size: 10m
    restart: unless-stopped
```

My problem is the client downloads the content to its own media folder instead of it being under the sonarr media folder. I assume sonarr is suppose to detect it but I don't think its being detected because rdt is returning the download as an error thus avoiding to do anything else. It errors in the web ui but the file is completely downloaded and fine.

Input string was not in a correct format. Failure to parse near offset 135. Format item ends prematurely.
