### ISSUE TITLE
Unable to deploy in Portainer

### ISSUE THREAD

**Issue by poweredtreble** [rogerfar/rdt-client#770]
Having issues getting this deployed as a stack in portainer. It gives me "missing signature key error", or to be exact:
```
Deployment error
Pulling rdtclient (rogerfar/rdtclient:2.0.102)... missing signature key
```
I copy pasted the docker compose script from the docker readme file (and modified it for my uid/gid/folders etc). The docker instructions don't seem to have been updated in 4 years - perhaps there's something that needs changing?

**Comment by Cucumberrbob** [comment]
What version of docker are you running? You can find out by running `docker version`.

**Comment by TimboZero** [comment]
Getting a similar problem (installing to portainer) but different error
```
Failed to deploy a stack: failed to load the compose file: service "rdtclient" refers to undefined volume &lt;path to data&gt;: invalid compose project
```

I did as advised above and checked my docker version
Client: Docker Engine - Community
 Version:           28.0.4
 API version:       1.48

i used the following compose script
```
---
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1000
      - PGID=100
      - TZ=CET
    volumes:
      - <path to data>:/NAS/AppData
      - <path to downloads>:/media
    ports:
      - 6500:6500
    restart: unless-stopped
```

Any help appreciated, thank you
