### ISSUE TITLE
No Symlink creation

### ISSUE THREAD

**Issue by Panagiotis-Zachos** [rogerfar/rdt-client#779]
**What version are you using?** v2.0.102

**What OS are you running?** Debian 12, bookworm

**Are you using Docker or as a service?** Docker

**Which debrid provider are you using?** real-debrid

**Which downloader are you using?** symlink

**Please attach a log file here with the log setting set to debug**

[rdtclient.log](https://github.com/user-attachments/files/19706121/rdtclient.log)
[zurg.log](https://github.com/user-attachments/files/19705968/rdtclient.log)

I get no errors anywhere, just testing with Radarr at the moment, which reports the torrent as Downloading. 

RDT-client reports that the torrent is finished, can see rdclone mount just fine. A Folder is created, but no file inside. 

Rdclone mount contains the file and can be accessed

**Comment by Cucumberrbob** [comment]
Version info and logs appear to be from Zurg. We don’t have great support for Zurg see also #750.

Can you post rdt-client logs and specify which version *of rdt-client* you’re using?

**Comment by Panagiotis-Zachos** [comment]
Oops, sorry my mistake, here are the rdtclient logs:
[rdtclient.log](https://github.com/user-attachments/files/19706121/rdtclient.log)

According to docker, I have the latest version, don't know where to find exact number though.

**Comment by Cucumberrbob** [comment]
If you restart the container and look at the logs, one of the first few lines logged includes the version iirc. Something along the lines of “starting rdt-client on version v2.0.x”

**Comment by Panagiotis-Zachos** [comment]
Ok, I tried doing everything from the start, after fixing some permission errors, here is the log-file: 

[rdtclient.log](https://github.com/user-attachments/files/19707048/rdtclient.log)

The torrent is reported as finished, however no symlink created.

**Comment by Cucumberrbob** [comment]
Where is your Zurg mount? It looks like you’re using `/opt/media` for both your downloads directory *and* your rclone mount path.

- - -

I think some error (not sure what) is causing the download to be unable to be started. When that happens, the download is marked as completed (it probably should be marked as error).

When I’ve got some time (probably later today), I’ll make a PR to improve the handling of errors here.

**Comment by Panagiotis-Zachos** [comment]
Maybe it would help if I included the docker-compose files, so here they are

``` 
---
version: '3.3'
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /opt/rdtc/data/db:/data/db
      - /mnt/zurg/__all__:/opt/media
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped
```

I have mapped the zurg mount to /opt/media, setting them all to /opt/media was the only way I could get it to work, but based on your last reply it seems I replaced one error with another. I will add another volume to the docker-compose file to separate zurg mount with the rdt-client download path.

**Comment by Cucumberrbob** [comment]
I think there’s a misconception here.

For symlink downloader users, we need 3 docker volumes: `/data/db`, `/data/downloads` (which you’ve changed in settings to be `/opt/media`, and `/mnt/rclone` (or whatever you have set Rclone Mount Path to).

The rclone (or in your case, Zurg) mount is not writable. We can only read the files, not move them or change them. That’s why we use the symlink downloader - a symlink is just an arrow pointing to another file.

So, when working normally, rdt-client will make a symlink in `/data/downloads` which points to a file in `/mnt/rclone`. This is part of the reason it’s a good idea not to “rename” this path (instead have it as `/mnt/zurg/__all__` in the container). That way every container and your host all interpret the symlink the same way.

Also, as a note on using `/opt/media`: rdt-client doesn’t need access to your media library. Sonarr/radarr will handle that. All rdt-client does is takes requests to download torrents from sonarr/radarr and gives them back files which they then put in the right place in your media library.

Here’s what I recommend for your docker compose:
```yaml
  volumes:
      - /opt/rdtc/data/db:/data/db
      - /home/Panagiotis/downloads/rdtc:/data/downloads
      - /mnt/zurg/__all__:/mnt/zurg/__all__
```
And update the paths in settings accordingly.

**Comment by Panagiotis-Zachos** [comment]
I updated the volumes like so:

```yaml
volumes:
  - /opt/rdtc/data/db:/data/db
  - /mnt/zurg/__all__:/mnt/zurg/__all__
  - /opt/media/downloads:/data/downloads
 ```

Also updated the paths in settings accordingly (I think):

Download path: /data/downloads
Mapped path: /data/downloads
Rclone mount path: /mnt/zurg/__all__

I am now getting the following error:  Could not find file from rclone mount! 

I guess the problem seems to be with zurg then?

**Comment by Panagiotis-Zachos** [comment]
I had put in the wrong local rclone mount path (doh), it's working now, radarr is picking up the symlinks and copying them to the appropriate folder.

Thank you SO much for your help and patience in this.

Just in case somebody tries to do the same thing as I did (using pd_zurg + rdt-client + *arrs * jellyfin) I will post the respective docker-compose files below.

Apart from that I had installed all the *arrs & Jellyfin using [swizzin](https://swizzin.ltd/)

(I know I have made a total mess with the paths, but this is the result of banging my head against the wall for 5 days)

pd_zurg:

```yaml
version: "3.8"

services:
  pd_zurg:
    container_name: pd_zurg
    image: iampuid0/pd_zurg:latest
    ## Optionally, specify a specific version of pd_zurg
    # image: iampuid0/pd_zurg:2.0.0
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true        # docker run -t   
    volumes:
      ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup. 
      - /opt/pd_zurg/config:/config
      ## Location for logs
      - /opt/pd_zurg/log:/log
      ## Location for rclone cache if enabled
      - /opt/pd_zurg/cache:/cache
      ## Location for Zurg RealDebrid active configuration
      - /opt/pd_zurg/RD:/zurg/RD
      ## Location for Zurg AllDebrid active configuration -- when supported by Zurg     
      - /opt/pd_zurg/AD:/zurg/AD
      ## Location for rclone mount to host
      - /opt/pd_zurg/mnt:/data:shared
    environment:
      - TZ=Germany/Berlin
      ## Zurg Required Settings
      - ZURG_ENABLED=true
      - RD_API_KEY=YOUR_RD_API_KEY_HERE
      ## Zurg Optional Settings
     # - ZURG_LOG_LEVEL=DEBUG
     # - ZURG_VERSION=v0.9.2-hotfix.4
     # - ZURG_UPDATE=true
     # - PLEX_REFRESH=true
     # - PLEX_MOUNT_DIR=/rclone/pd_zurg 
     # - ZURG_USER=
     # - ZURG_PASS=
     # - ZURG_PORT=8800
      ## Rclone Required Settings
      - RCLONE_MOUNT_NAME=pd_zurg
      ## Rclone Optional Settings - See rclone docs for full list
      - RCLONE_UID=1000
      - RCLONE_GID=1000
     # - NFS_ENABLED=true
     # - NFS_PORT=8000
     # - RCLONE_LOG_LEVEL=DEBUG
     # - RCLONE_CACHE_DIR=/cache
     # - RCLONE_DIR_CACHE_TIME=10s
     # - RCLONE_VFS_CACHE_MODE=full
     # - RCLONE_VFS_CACHE_MAX_SIZE=100G
     # - RCLONE_ATTR_TIMEOUT=8700h
     # - RCLONE_BUFFER_SIZE=32M
     # - RCLONE_VFS_CACHE_MAX_AGE=4h
     # - RCLONE_VFS_READ_CHUNK_SIZE=32M
     # - RCLONE_VFS_READ_CHUNK_SIZE_LIMIT=1G
     # - RCLONE_TRANSFERS=8
      ## Plex Debrid Required Settings
      - PD_ENABLED=true
      ## To utilize plex_debrid with Plex, the following environment variables are required
      #- PLEX_USER=
      #- PLEX_TOKEN=
      #- PLEX_ADDRESS=
      ## To utilize plex_debrid with Jellyfin, the following environment variables are required - Note that plex_debrid will require addtional setup befor use with Jellyfin
      - JF_ADDRESS=YOUR_ADDRESS_HERE
      - JF_API_KEY=YOUR_JELLYFIN_API_HERE
      ## Plex Debrid Optional Settings
     # - PD_UPDATE=true # only works when PD_REPO set
     # - PD_REPO=itsToggle,plex_debrid,main
     # - SHOW_MENU=false
     # - SEERR_API_KEY=
     # - SEERR_ADDRESS=
      ## Special Features
     # - AUTO_UPDATE_INTERVAL=12
     # - DUPLICATE_CLEANUP=true
     # - CLEANUP_INTERVAL=1
     # - PDZURG_LOG_LEVEL=DEBUG
     # - PDZURG_LOG_COUNT=2
     # - PDZURG_LOG_SIZE=10M
    # Example to attach to gluetun vpn container if realdebrid blocks IP address 
    # network_mode: container:gluetun  
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
```

rdtclient:
```yaml
---
version: '3.3'
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /opt/rdtc/data/db:/data/db
      - /opt/pd_zurg/mnt/pd_zurg/__all__/:/mnt/zurg/__all__
      - /opt/media/downloads:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped
```
